#! /bin/bash
#
$Author: ee364g13 $
$Date: 2016-01-13 14:42:58 -0500 (Wed, 13 Jan 2016) $
$HeadURL: svn+ssh://ece364sv@ecegrid-thin1/home/ecegrid/a/ece364sv/svn/S16/students/ee364g13/Lab00/testheader $
$Revision: 84669 $